kafka:
  image: antlypls/kafka
  environment:
      - KAFKA=localhost:9092
      - ZOOKEEPER=localhost:2181
  ports:
        - "9092:9092"
        - "2181:2181"
  expose:
      - "2181"
      - "9092"

spark:
  image: antlypls/spark:1.6.0
  ports:
          - "4040:4040"
  command: bash
  volumes:
    - ./target/scala-2.11:/app
  links:
    - kafka